services:
  web-services-db:
    image: mariadb:11
    container_name: web-services-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_DOCKER_PORT}
    volumes:
      - web-services-db_data:/var/lib/mysql
      - './skyjo_src/src/main/resources/db/migration/V1__initial_model.sql:/docker-entrypoint-initdb.d/V1__initial_model.sql'
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  benutzerverwaltung:
    build:
      context: ./benutzerverwaltung_src
      dockerfile: Dockerfile
    container_name: benutzerverwaltung
    restart: unless-stopped
    depends_on:
      web-services-db:
        condition: service_healthy

    env_file:
      - ./.env

    environment:
      DB_HOST: web-services-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
    ports:
      - ${BENUTZERVERWALTUNG_DOCKER_PORT}

  matchmaking:
    build:
      context: ./matchmaking_src
      dockerfile: Dockerfile
    container_name: matchmaking
    restart: unless-stopped
    depends_on:
      web-services-db:
        condition: service_healthy
    
    env_file:
      - ./.env

    environment:
      DB_HOST: web-services-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
    ports:
      - ${MATCHMAKING_DOCKER_PORT}
      - ${MATCHMAKING_DOCKER_WS_PORT}

  color-api:
    build: 
      context: ./color-api_src
      dockerfile: Dockerfile
    container_name: color-api
    restart: unless-stopped
    depends_on:
      web-services-db:
        condition: service_healthy
    
    env_file:
      - ./.env

    environment:
      APP_PORT: ${COLOR_API_PORT}
      DB_HOST: web-services-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_POOL_SIZE: 5
      DB_POOL_CREATE_RETRIES: 20

    ports:
      - ${COLOR_API_DOCKER_PORT}

  skyjo-logic: 
    build: 
      context: ./skyjo_src
      dockerfile: Dockerfile
    restart: on-failure

    env_file:
      - ./.env

    environment:
      DB_HOST: web-services-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${SKYJO_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      # Add this to ensure the Quarkus runtime also knows where the DB is
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mariadb://web-services-db:${DB_PORT}/${SKYJO_DATABASE}

    ports:
      - ${SKYJO_DOCKER_PORT}
    depends_on:
      web-services-db:
        condition: service_healthy
    

volumes:
  web-services-db_data: