ALTER TABLE action
    MODIFY COLUMN action_type VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    MODIFY COLUMN newCardInField BOOLEAN NOT NULL DEFAULT 0,
    MODIFY COLUMN drawPile BOOLEAN NOT NULL DEFAULT 0;